const loginFields = [
  {
    labelText: "Email address",
    labelFor: "userName",
    id: "userName",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];
const bookFormFields = [
  {
    labelText: "Book Titile",
    labelFor: "Book Titile",
    id: "bookTitile",
    name: "bookTitile",
    type: "text",
    // autoComplete: "current-password",
    isRequired: true,
    placeholder: "bookTitle",
  },
  {
    labelText: "Author Name",
    labelFor: "Author Name",
    id: "authorName",
    name: "authorName",
    type: "text",
    // autoComplete: "current-password",
    isRequired: true,
    placeholder: "Author Name",
  },
  {
    labelText: "Publication Date",
    labelFor: "Publication Date",
    id: "publicationDate",
    name: "publicationDate",
    type: "Date",
    // autoComplete: "current-password",
    isRequired: true,
    placeholder: "Publication Date",
  },
  {
    labelText: "ISBN Number",
    labelFor: "ISBN Number",
    id: "isbnNumber",
    name: "isbnNumber",
    type: "Text",
    // autoComplete: "current-password",
    isRequired: true,
    placeholder: "ISBN Number",
  },
];
export { loginFields, bookFormFields };
